version: '3.4'

services:
  boardmanager:
    image: ${DOCKER_REGISTRY-}boardmanager
    build:
      context: .
      dockerfile: BoardManager/Dockerfile
    deploy:
      replicas: 1
    volumes:
      - ./cloudAMQPConnectionString.txt:/app/cloudAMQPConnectionString.txt
    depends_on:
      - gamemanager

  botai:
    image: ${DOCKER_REGISTRY-}botai
    build:
      context: .
      dockerfile: BotAI/Dockerfile
    deploy:
      replicas: 2
    volumes:
      - ./cloudAMQPConnectionString.txt:/app/cloudAMQPConnectionString.txt
    depends_on:
      - gamemanager

  gamemanager:
    image: ${DOCKER_REGISTRY-}gamemanager
    build:
      context: .
      dockerfile: GameManager/Dockerfile
    volumes:
      - ./cloudAMQPConnectionString.txt:/app/cloudAMQPConnectionString.txt
    depends_on:
        loki:
            condition: service_healthy

  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  loki:
    image: grafana/loki:master
    ports:
        - 3100:3100
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3100/ready
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  grafana:
    image: grafana/grafana:master
    ports:
        - 3000:3000
    depends_on:
        loki:
            condition: service_healthy